### ISSUE TITLE
Does not build on ARM

### ISSUE THREAD

**Issue by jdidion** [delocalizer/streammd#24]
Compilation fails due to inclusion of `immintrin.h`. It looks like this can be fixed pretty easily. See e.g. https://github.com/coin-or/Clp/issues/127.

**Comment by delocalizer** [comment]
Thanks for reporting, and for the hint on a fix.

**Comment by delocalizer** [comment]
To help repro can I ask:
1) which particular ARM arch is this failing on?
2) are you using a distributed release tarball (and which?)

**Comment by jdidion** [comment]
This is a Mac M1 Max. I used the [4.0.2 release tarball ](https://github.com/delocalizer/streammd/releases/download/4.0.2/streammd-4.0.2.tar.gz).

**Comment by delocalizer** [comment]
Please try again with version [4.1.0](https://github.com/delocalizer/streammd/releases/tag/4.1.0)

**Comment by delocalizer** [comment]
I'll close this as I've had reports from others that versions 4.1.1 and onwards build and test successfully on M1 Mac. Please do reopen if this is not the case for you. Better, I'll set up some cross-compile environments and test before future releases.

**Comment by jdidion** [comment]
Thanks, I can confirm that it works for me.
