### ISSUE TITLE
Add streammd to bioconda clouds

### ISSUE THREAD

**Issue by xiekunwhy** [delocalizer/streammd#36]
Hi,

streammd is a great tool, but it is not so easy to compile in some system environments, would you please add it to bioconda clouds?

Best,
Kun

**Comment by delocalizer** [comment]
Thanks for the suggestion; I'll add it as a TODO. Additionally, please do log an issue here if you encounter a problem compiling the project for a specific environment. It could be you've encountered a platform-specific issue that needs fixing.
